image: Visual Studio 2017
environment:
  RUSTFLAGS: -Ctarget-feature=+crt-static
  RUST_BACKTRACE: 1
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    ALLOW_PR: 1
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
    MINGW_DIR: mingw64
  - TARGET: i686-pc-windows-gnu
    MINGW_DIR: mingw32
  access_token:
    secure: q8Wqx0brgfpOYFQqWauvucE2h0o1WYb41a3gKaCKV9QiE4eTz6qLNlqyC3mdsp4Q
branches:
  only:
    - master
    - stable
    - auto

install:
  # If this is a PR and we're not allowed to test PRs, skip the whole build.
  # Also if we're on the master branch no need to run the full test suite, so
  # just do a smoke test.
  - if defined APPVEYOR_PULL_REQUEST_NUMBER if NOT defined ALLOW_PR appveyor exit
  - if "%APPVEYOR_REPO_BRANCH%" == "master" if NOT defined ALLOW_PR appveyor exit

  # Install MSYS2 and MINGW (32-bit & 64-bit)
  - ps: |
      # Check if MSYS2 was restored from cache
      if($env:MINGW_DIR) {
        if($env:MINGW_DIR -eq "mingw32") {
          # Download and install MINGW (32-bit)
          Write-Host "Installing MinGW (32-bit)..." -ForegroundColor Cyan
          Write-Host "Downloading installation package..."
          appveyor-retry appveyor DownloadFile https://s3.amazonaws.com/rust-lang-ci/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z -FileName mingw.7z
        } elseif($env:MINGW_DIR -eq "mingw64") {
          # Download and install MINGW (64-bit)
          Write-Host "Installing MinGW (64-bit)..." -ForegroundColor Cyan
          Write-Host "Downloading installation package..."
          appveyor-retry appveyor DownloadFile https://s3.amazonaws.com/rust-lang-ci/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z -FileName mingw.7z
        }
        Write-Host "Extracting installation package..."
        7z x -y mingw.7z -oC:\msys64 | Out-Null
        del mingw.7z
      } else {
        Write-Host "MSYS2 not required" -ForegroundColor Green
      }

  # Install rust, x86_64-pc-windows-msvc host
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host=x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - del rustup-init.exe

  # Install the target we're compiling for
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%

  # add mingw to PATH if necessary
  - if defined MINGW_DIR set PATH=C:\msys64\%MINGW_DIR%\bin;C:\msys64\usr\bin;%PATH%
  # And if mingw, re-put appveyor's git in place
  - if defined MINGW_DIR set PATH=C:\Program Files\Git\cmd;%PATH%

  # let's see what we got
  - where gcc rustc cargo
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --release --target %TARGET% --locked
  - cargo run --release --target %TARGET% --locked -- --dump-testament
  - cargo test --release --target %TARGET%

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/9907ad94eb7a5ff291c3

after_test:
  - powershell -File ci/prepare-deploy-appveyor.ps1

artifacts:
  - path: dist\$(TARGET)\rustup-init.exe
    name: rustup-init
  - path: dist\$(TARGET)\rustup-init.exe.sha256
    name: rustup-init-sha
  - path: dist\$(TARGET)\rustup-setup.exe
    name: rustup-setup
  - path: dist\$(TARGET)\rustup-setup.exe.sha256
    name: rustup-setup-sha

deploy:
  - provider: S3
    skip_cleanup: true
    access_key_id: $(AWS_ACCESS_KEY_ID)
    secret_access_key: $(AWS_SECRET_ACCESS_KEY)
    bucket: dev-static-rust-lang-org
    set_public: true
    region: us-west-1
    artifact: rustup-init,rustup-init-sha,rustup-setup,rustup-setup-sha
    folder: rustup
    on:
      branch: stable
