environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
    BITS: 64
  - TARGET: i686-pc-windows-gnu
    BITS: 32
  access_token:
    secure: CZlbQEamQxfTbQJlLl/3QfVLhVxk+1sBFMxuCN3dwHKeGHNBSE4tQudXSJ5n0Z6P
branches:
  only:
    - master
    - new
install:
  - ps: |
      # Install Rust
      Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe" -FileName "rust-nightly.exe"
      .\rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
      $env:PATH="$env:PATH;C:\rust\bin"

      New-Item .cargo -type directory
      Copy-Item .appveyor.cargo-config.toml .cargo/config

      # For -gnu builds
      if ($env:TARGET -match "-gnu$") {
        $env:PATH="$env:PATH;C:\msys64\mingw${env:BITS}\bin"
      }

      # For -msvc builds
      if ($env:TARGET -match "-msvc$") {
        Start-FileDownload "http://www.npcglib.org/~stathis/downloads/openssl-1.0.2d-vs2015.7z" -FileName "openssl.7z"
        7z x openssl.7z -o"C:\OpenSSL" | Out-Null
      }

      # Print version info
      rustc -vV
      cargo -vV

      # Configure git
      git config --global user.email "diggsey@googlemail.com"
      git config --global user.name "Diggory Blake (via Appveyor CI)"
      git config --global push.default simple

build: false
test_script:
  - cargo build --release
  - cargo test
  - cargo test -p rust-install
  - cargo test -p rust-manifest
  - tests\cli.bat
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/9907ad94eb7a5ff291c3
on_success:
  - ps: |
      if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) {
        cargo build --release
        # Generate hashes
        Get-FileHash .\target\release\* | ForEach-Object {[io.file]::WriteAllText($_.Path + ".sha256", $_.Hash.ToLower() + "`n")}

        if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
          $bin = "binaries\$env:TARGET"
        } else {
          $bin = "binaries\$env:APPVEYOR_REPO_BRANCH\$env:TARGET"
        }

        cmd /c "git config --global credential.helper store 2>&1"
        Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
        cmd /c "git submodule init 2>&1"
        cmd /c "git submodule update --depth 1 --remote 2>&1"
        if (!(Test-Path -Path "$bin")) { mkdir "$bin" }
        cmd /c "del /Q `"$bin`""
        cmd /c "copy /B /Y `"target\release\*`" `"$bin`""
        cmd /c "git rev-parse HEAD > `"$bin\commit.txt`" 2>&1"
        cd binaries
        cmd /c "git checkout master 2>&1"
        cmd /c "git add -A 2>&1"
        cmd /c "git commit -m `"Auto-update $env:APPVEYOR_REPO_BRANCH/$env:TARGET binaries (Appveyor CI)`" 2>&1"
        $attempts = 1; do { .\push-changes.bat; $attempts++ } while($lastexitcode -ne '0' -and $attempts -le 5)
      }
