[package]

name = "rustup-utils"
version = "1.0.0"
authors = [ "Diggory Blake <diggsey@googlemail.com>" ]
description = "multirust in rust - manage multiple rust installations with ease"

documentation = "http://rust-lang-nursery.github.io/rustup.rs/rustup_utils/index.html"
homepage = "https://github.com/rust-lang-nursery/rustup.rs"
repository = "https://github.com/rust-lang-nursery/rustup.rs"

license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.3.11"
scopeguard = "0.1.2"
error-chain = "0.7.1"
libc = "0.2.0"
rustc-serialize = "0.3.19"
sha2 = "0.1.2"
url = "1.1"
toml = "0.1.27"
semver = "0.4.0"
download = { path = "../download" }

[target."cfg(windows)".dependencies]
winapi = "0.2.8"
winreg = "0.3.2"
shell32-sys = "0.1.1"
ole32-sys = "0.2.0"
kernel32-sys = "0.2.1"
advapi32-sys = "0.2.0"
userenv-sys = "0.2.0"

