[package]
name = "rustup-win-installer"
version = "1.0.0"
authors = ["Patrick Reisert"]
build = "build.rs"

[lib]
name = "rustup_msi"
crate-type = ["cdylib"]

[dependencies]
winapi = "0.2"
rustup = { path = "../../", version = "1.0.0" }
