[book]
authors = ["The Rust Project Developers"]
language = "en"
title = "The Rustup developer guide"

[output.html]
edit-url-template = "https://github.com/rust-lang/rustup/edit/HEAD/doc/dev-guide/{path}"
git-repository-url = "https://github.com/rust-lang/rustup/tree/HEAD/doc/dev-guide"
site-url = "https://rust-lang.github.io/rustup/dev-guide"
