[book]
authors = ["The Rust Project Developers"]
title = "The rustup book"

[output.html]
edit-url-template = "https://github.com/rust-lang/rustup/edit/HEAD/doc/user-guide/{path}"
git-repository-url = "https://github.com/rust-lang/rustup/tree/HEAD/doc/user-guide"
site-url = "https://rust-lang.github.io/rustup/"

[output.html.redirect]
"/installation/package-managers.html" = "already-installed-rust.html"
