[package]

name = "download"
version = "0.6.0"
edition = "2018"
authors = [ "Brian Anderson <banderson@mozilla.com>" ]

license = "MIT/Apache-2.0"

[features]

default = ["reqwest-backend"]

curl-backend = ["curl"]
reqwest-backend = ["reqwest", "env_proxy", "lazy_static"]

[dependencies]
error-chain = "0.12"
url = "1.7"
curl = { version = "0.4.11", optional = true }
env_proxy = { version = "0.3.1", optional = true }
lazy_static = { version = "1.0", optional = true }
reqwest = { version = "0.9.14", features = ["socks"], optional = true }

[dev-dependencies]
futures = "0.1"
hyper = "0.12"
tempdir = "0.3.4"
