[package]

authors = ["Brian Anderson <banderson@mozilla.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "download"
version = "1.25.1"

[features]

default = ["reqwest-backend", "reqwest-rustls-tls", "reqwest-default-tls"]

curl-backend = ["curl"]
reqwest-backend = ["reqwest", "env_proxy", "lazy_static"]
reqwest-default-tls = ["reqwest/default-tls"]
reqwest-rustls-tls = ["reqwest/rustls-tls-native-roots"]

[dependencies]
anyhow = "1.0.68"
curl = {version = "0.4.44", optional = true}
env_proxy = {version = "0.4.1", optional = true}
lazy_static = {version = "1.0", optional = true}
reqwest = {version = "0.11", default-features = false, features = ["blocking", "gzip", "socks"], optional = true}
thiserror = "1.0"
url = "2.1"

[dev-dependencies]
hyper = {version = "0.14", default-features = false, features = ["tcp", "server"]}
tempfile = "3"
tokio = {version = "1", default-features = false, features = ["sync"]}
