[package]

name = "download"
version = "0.6.5"
edition = "2018"
authors = [ "Brian Anderson <banderson@mozilla.com>" ]

license = "MIT/Apache-2.0"

[features]

default = ["reqwest-backend"]

curl-backend = ["curl"]
reqwest-backend = ["reqwest", "env_proxy", "lazy_static"]

[dependencies]
error-chain = "0.12"
url = "2.1"
curl = { version = "0.4.11", optional = true }
env_proxy = { version = "0.4", optional = true }
lazy_static = { version = "1.0", optional = true }
reqwest = { version = "0.10", features = ["blocking", "gzip"], optional = true }

[dev-dependencies]
hyper = "0.13"
tempfile = "3"
tokio = { version = "0.2" }
