[package]

name = "download"
version = "0.6.8"
edition = "2018"
authors = [ "Brian Anderson <banderson@mozilla.com>" ]

license = "MIT/Apache-2.0"

[features]

default = ["reqwest-backend", "reqwest-rustls-tls", "reqwest-default-tls"]

curl-backend = ["curl"]
reqwest-backend = ["reqwest", "env_proxy", "lazy_static"]
reqwest-default-tls = ["reqwest/default-tls"]
reqwest-rustls-tls = ["reqwest/rustls-tls-native-roots"]

[dependencies]
error-chain = "0.12"
url = "2.1"
curl = { version = "0.4.11", optional = true }
env_proxy = { version = "0.4.1", optional = true }
lazy_static = { version = "1.0", optional = true }
reqwest = { version = "0.10.9", default-features = false, features = ["blocking", "gzip", "socks"], optional = true }

[dev-dependencies]
hyper = { version = "0.13", default-features = false, features = ["tcp"] }
tempfile = "3"
tokio = { version = "0.2.2", default-features = false, features = ["tcp", "sync"] }
