name: General Checks

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
      - stable
  schedule:
    - cron: "30 0 * * 1" # Every Monday at half past midnight

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          # v2 defaults to a shallow checkout, but we need at least to the previous tag
          fetch-depth: 0
      - name: Acquire tags for the repo
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Display the current git status
        run: |
          git status
          git describe

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Get rustc commit hash
        id: cargo-target-cache
        run: |
          echo "::set-output name=rust_hash::$(rustc -Vv | grep commit-hash | awk '{print $2}')"
        shell: bash
      - name: Cache build dir
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-beta-target-dir-${{ steps.cargo-target-cache.outputs.rust_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rustup using ./rustup-init.sh
        run: |
          sh ./rustup-init.sh --default-toolchain=none --profile=minimal -y
      - name: Ensure Beta is up to date
        run: |
          rustup update beta
          rustup default beta
      - run: rustup component add rustfmt clippy

      - name: Run the centos check within the docker image
        run: |
          HERE=$(pwd)
          docker run \
            --volume "$HERE":/checkout:ro \
            --workdir /checkout \
            --tty \
            --init \
            --rm \
            centos:6 \
            sh ./ci/raw_init.sh

      - name: Run shell checks
        run: |
          shellcheck -s dash -- rustup-init.sh
          git ls-files -- '*.sh' | xargs shellcheck -s dash -e SC1090
          git ls-files -- '*.bash' | xargs shellcheck -s bash -e SC1090

      - name: Run formatting checks
        run: cargo fmt -- --check

      - name: Run cargo check and clippy
        run: |
          cargo check --all --all-targets
          git ls-files -- '*.rs' | xargs touch
          cargo clippy --all --all-targets

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
